# Manifest file that destribes kubernetes 'deployments' and supprting 'services' 
# for any Fastscore 'engines' necessary for the deployment
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: engine-1
  labels:
    service: engine-1
    app: engine-1
    stack: fastscore
spec:
  replicas: 1
  template:
    metadata:
      annotations:
      labels:
        service: engine-1
        app: engine-1
        stack: fastscore
    spec:
      containers:
      - name: engine-1
        env:
        - name: CONNECT_PREFIX
          value: https://connect:8001
        image: fastscore/engine:1.9
        # Use the resources section to request to be deployed to a node with enough resources for your model (if necessary)
        resources:
          requests:
            cpu: 
            memory:
        volumeMounts:
        #Fastscore engines write to the following directories during normal operation
        - mountPath: /fastscore/log
          name: log-dir
        - mountPath: /tmp
          name: temp-dir
        ports:
        - containerPort: 8003
          protocol: TCP
        resources: {}
        stdin: true
        tty: true
      imagePullSecrets:
      - name: regcred
      volumes:
      - emptyDir: {}
        name: log-dir
      - emptyDir: {}
        name: temp-dir
      restartPolicy: Always
status: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    service: engine-1
    app: engine-1
    stack: fastscore
  name: engine-1
spec:
  ports:
  - name: 8003-tcp
    port: 8003
    protocol: TCP
    targetPort: 8003
  selector:
    service: engine-1
    app: engine-1
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: engine-2
  labels:
    service: engine-2
    app: engine-2
    stack: fastscore
spec:
  replicas: 1
  template:
    metadata:
      annotations:
      labels:
        service: engine-2
        app: engine-2
        stack: fastscore
    spec:
      containers:
      - name: engine-2
        env:
        - name: CONNECT_PREFIX
          value: https://connect:8001
        image: fastscore/engine:1.9
        # Use the resources section to request to be deployed to a node with enough resources for your model (if necessary)
        resources:
          requests:
            cpu: 
            memory:
        volumeMounts:
        #Fastscore engines write to the following directories during normal operation
        - mountPath: /fastscore/log
          name: log-dir
        - mountPath: /tmp
          name: temp-dir
        ports:
        - containerPort: 8003
          protocol: TCP
        resources: {}
        stdin: true
        tty: true
      imagePullSecrets:
      - name: regcred
      volumes:
      - emptyDir: {}
        name: log-dir
      - emptyDir: {}
        name: temp-dir
      restartPolicy: Always
status: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    service: engine-2
    app: engine-2
    stack: fastscore
  name: engine-2
spec:
  ports:
  - name: 8003-tcp
    port: 8003
    protocol: TCP
    targetPort: 8003
  selector:
    service: engine-2
    app: engine-2
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: engine-3
  labels:
    service: engine-3
    app: engine-3
    stack: fastscore
spec:
  replicas: 1
  template:
    metadata:
      annotations:
      labels:
        service: engine-3
        app: engine-3
        stack: fastscore
    spec:
      containers:
      - name: engine-3
        env:
        - name: CONNECT_PREFIX
          value: https://connect:8001
        image: fastscore/engine:1.9
        # Use the resources section to request to be deployed to a node with enough resources for your model (if necessary)
        resources:
          requests:
            cpu: 
            memory:
        volumeMounts:
        #Fastscore engines write to the following directories during normal operation
        - mountPath: /fastscore/log
          name: log-dir
        - mountPath: /tmp
          name: temp-dir
        ports:
        - containerPort: 8003
          protocol: TCP
        resources: {}
        stdin: true
        tty: true
      imagePullSecrets:
      - name: regcred
      volumes:
      - emptyDir: {}
        name: log-dir
      - emptyDir: {}
        name: temp-dir
      restartPolicy: Always
status: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    service: engine-3
    app: engine-3
    stack: fastscore
  name: engine-3
spec:
  ports:
  - name: 8003-tcp
    port: 8003
    protocol: TCP
    targetPort: 8003
  selector:
    service: engine-3
    app: engine-3
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
